
title: Rini Varghese
email: rvarghe9@jhmi.edu
description: "Welcome to my personal website"
baseurl: "rinivarg.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rinivarg
github_username: rinivarg

# Build settings
# markdown: kramdown
theme: minima #jekyll-theme-tactile

include:
  - _pages
# Other options
# permalink: "/:year"