
title: Rini Varghese
email: rvarghe9@jhmi.edu
description: "Welcome to my personal website"
baseurl: "/about" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rinivarg
github_username: rinivarg

# Build settings
theme: jekyll-theme-tactile #jekyll-theme-tactile
# markdown: kramdown

include:
  - _pages
# Other options
# permalink: "blog/:year/:month/:title"